# Generated by Django 5.0.3 on 2024-04-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_doctor_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.JSONField(default={'Friday': [{'end': '9:30', 'start': '9:00'}, {'end': '10:00', 'start': '9:30'}, {'end': '10:30', 'start': '10:00'}, {'end': '11:00', 'start': '10:30'}, {'end': '11:30', 'start': '11:00'}, {'end': '13:30', 'start': '13:00'}, {'end': '14:00', 'start': '13:30'}, {'end': '14:30', 'start': '14:00'}, {'end': '15:00', 'start': '14:30'}, {'end': '15:30', 'start': '15:00'}, {'end': '16:00', 'start': '15:30'}, {'end': '16:30', 'start': '16:00'}, {'end': '17:00', 'start': '16:30'}], 'Monday': [{'end': '9:30', 'start': '9:00'}, {'end': '10:00', 'start': '9:30'}, {'end': '10:30', 'start': '10:00'}, {'end': '11:00', 'start': '10:30'}, {'end': '11:30', 'start': '11:00'}, {'end': '13:30', 'start': '13:00'}, {'end': '14:00', 'start': '13:30'}, {'end': '14:30', 'start': '14:00'}, {'end': '15:00', 'start': '14:30'}, {'end': '15:30', 'start': '15:00'}, {'end': '16:00', 'start': '15:30'}, {'end': '16:30', 'start': '16:00'}, {'end': '17:00', 'start': '16:30'}], 'Thursday': [{'end': '9:30', 'start': '9:00'}, {'end': '10:00', 'start': '9:30'}, {'end': '10:30', 'start': '10:00'}, {'end': '11:00', 'start': '10:30'}, {'end': '11:30', 'start': '11:00'}, {'end': '13:30', 'start': '13:00'}, {'end': '14:00', 'start': '13:30'}, {'end': '14:30', 'start': '14:00'}, {'end': '15:00', 'start': '14:30'}, {'end': '15:30', 'start': '15:00'}, {'end': '16:00', 'start': '15:30'}, {'end': '16:30', 'start': '16:00'}, {'end': '17:00', 'start': '16:30'}], 'Tuesday': [{'end': '9:30', 'start': '9:00'}, {'end': '10:00', 'start': '9:30'}, {'end': '10:30', 'start': '10:00'}, {'end': '11:00', 'start': '10:30'}, {'end': '11:30', 'start': '11:00'}, {'end': '13:30', 'start': '13:00'}, {'end': '14:00', 'start': '13:30'}, {'end': '14:30', 'start': '14:00'}, {'end': '15:00', 'start': '14:30'}, {'end': '15:30', 'start': '15:00'}, {'end': '16:00', 'start': '15:30'}, {'end': '16:30', 'start': '16:00'}, {'end': '17:00', 'start': '16:30'}], 'Wednesday': [{'end': '9:30', 'start': '9:00'}, {'end': '10:00', 'start': '9:30'}, {'end': '10:30', 'start': '10:00'}, {'end': '11:00', 'start': '10:30'}, {'end': '11:30', 'start': '11:00'}, {'end': '13:30', 'start': '13:00'}, {'end': '14:00', 'start': '13:30'}, {'end': '14:30', 'start': '14:00'}, {'end': '15:00', 'start': '14:30'}, {'end': '15:30', 'start': '15:00'}, {'end': '16:00', 'start': '15:30'}, {'end': '16:30', 'start': '16:00'}, {'end': '17:00', 'start': '16:30'}]}),
        ),
    ]
