# Generated by Django 5.0.3 on 2024-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_appointment_appointment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='current_load',
            field=models.IntegerField(default=0),
        ),
    ]
