# Generated by Django 5.0.3 on 2024-05-08 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_appointment_queue_position_doctor_current_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='urgency',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
