# Generated by Django 5.0.3 on 2024-05-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_appointment_scheduled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
