# Generated by Django 5.0.3 on 2024-06-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_appointment_location_wait_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimated_start_service_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location_wait_time',
            field=models.IntegerField(),
        ),
    ]
