# Generated by Django 5.0.3 on 2024-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
