# Generated by Django 5.0.3 on 2024-04-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default='Internal medicine', max_length=50),
        ),
    ]
